### ISSUE TITLE
[BUG]The scrollbar is not affected by the theme mode

### ISSUE THREAD

**Issue by llity** [tefkah/zotero-night#69]
**Describe the bug**
The scrollbar is not affected by the theme mode.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/11771112/190885594-2e621991-b496-436d-a3cd-46d558bb3260.png">

**Comment by tefkah** [comment]
This is the same as #40, so I'm closing it in favor of that. Short answer: the version of firefox used by Zotero does not support scrollbar theming, so unless I reimplement all the scrollbars (which I might do at some point) I don't think there's a way to do it without setting your system theme to dark.

However, since you are on a Mac, you can set "Scrollbar behavior" to "When scrolling", 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/21983833/191064033-25e58751-cb42-4c4f-a979-892844bf9a7f.png">
which will make them hidden by default and look way more natural when scrolling (like this)
<img width="526" alt="image" src="https://user-images.githubusercontent.com/21983833/191064235-2919576f-728c-4d87-b5fb-c2b967d87f0b.png">

This unfortunately cannot be set on a per-app basis i think :(
